### ISSUE TITLE
difficulties with boost

### ISSUE THREAD

**Issue by bgriffen** [simongibbons/pyfof#6]
Could you please provide your environment file or package list as boost is notoriously difficult to install properly. I've tried multiple variations but still boost is unable to be found by pyfof. Would you have a working yaml file you might be able to share? (Ubuntu 16.04, Python 2.7) Thanks.

**Comment by bgriffen** [comment]
Better late than never =). Any luck on this one? I was just revisiting and was curious to give it a try on some data I've got. It also doesn't seem to work on OSX Anaconda with fresh environment python 3.7+boost. Any ideas?

**Comment by simongibbons** [comment]
Hi Brendan, thanks for the poke and sorry I've taken a while to get back to you.

I'm afraid I'm not too familiar with conda environments, however I am handy with docker.

I've added some build scripts which will build 2.7/3.6/3.7 wheels on linux

See the commit https://github.com/simongibbons/pyfof/commit/9e62313af1ee78382dc8b0165d27369ce7498007

Let me know if this helps you, when I get more time I can see if I can get conda working (I've been meaning to try it out sometime anyway!) then I should be able to help you more.

If you can use these dockerfiles to get an anaconda environment we can commit here that would be even better.

**Comment by simongibbons** [comment]
if you have docker installed on linux it should be as simple as calling `./build_linux_wheels.sh` to build them

**Comment by Astrokiwi** [comment]
I'm having the same issues. boost is installed in /usr/include/boost/, and it looks like your script counts that as a default location and should be able to find it there, but it doesn't. Is the `pip` version out of date?

i was however able to install it from `./build_linux_wheels.sh`, but I had to install docker first.

**Comment by holophrasm** [comment]
Hi, chiming in with the same issue. would really appreciate it if you could look into getting conda working.

**Comment by simongibbons** [comment]
Hi both. I've finally found some time for this.

I've updated the boost discovery process so that it should play nicely with conda.

Additionally I've put together an conda environment file which will produce a build

```yaml
name: pyfof
channels:
  - conda-forge
dependencies:
 - boost-cpp=1.64
 - cython=0.29
 - numpy=1.16
 - gcc_linux-64
 - gxx_linux-64
 - python=3.6
```

let me know if that helps

**Comment by simongibbons** [comment]
Another update on this. I've worked out the issue with modern boost. `master` should compile fine with the latest stable boost.

Let me know if this gives you any more trouble.

Best,

Simon
