### ISSUE TITLE
failure to install on Mac 

### ISSUE THREAD

**Issue by holophrasm** [simongibbons/pyfof#8]
pip is able to find where my boost is, however, pip install pyfof returns:

"    pyfof/pyfof.cpp:640:10: fatal error: 'ios' file not found
  #include "ios"

Failed building wheel for pyfof"

" 2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1"

There are also warnings about using deprecated NumPy API and "pass '-stdlib=libc++' on the command line to use the libc++ standard library instead"

**Comment by simongibbons** [comment]
Hi @holophrasm sorry for taking a while to reply - I haven't had much time to maintain this.

Which version of boost are you using. I've recently discovered that pyfof is incompatible with boost >=1.65

If you can install 1.64 you should get a build working. I'll try to find some time to make this work with a modern boost, but I can't guarantee I'll be able to find the time.

Best,

Simon

**Comment by simongibbons** [comment]
:man_facepalming: turns out I was missing an include which was causing the issue.

master should build with the latest stable boost now. I should also cut a release and put it on pypi as that hasn't been updated in quite a while.

**Comment by guotsuan** [comment]
With extra option: CFLAGS='-stdlib=libc++' pip install pyfof I can install pyfof on macosX
